apiVersion: v2
name: marmot
description: Marmot is an open-source data catalog that helps teams discover, understand, and govern their data assets. It's designed for modern data ecosystems where data flows through multiple systems, formats and teams.
type: application
version: 1.5.0
appVersion: "0.10.0"
icon: https://marmotdata.github.io/charts/marmot.png
home: https://github.com/marmotdata/marmot
sources:
  - https://github.com/marmotdata/marmot
maintainers:
  - name: The Marmot Authors
    email: support@marmotdata.io
keywords:
  - marmot
  - data
  - data catalog
  - lineage
  - catalog
  - data discovery
  - data governance
  - metadata
  - data lineage
  - observability
  - openlineage
  - kubernetes
  - postgresql
