{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "marmot.postgresqlHeadlessServiceName" . }}
  labels:
    {{- include "marmot.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "marmot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
